### ISSUE TITLE
Question: Naming convention?

### ISSUE THREAD

**Issue by legman** [sos-tactical-gaming/PorpoiseJockey#6]
I have started with my usual **LM**. Are we happy with that or would we prefer something else for example...

**SOS**
**DC**
**PJ**

If people don't like **LM** my vote goes with **DC**.

**Comment by OzoBro** [comment]
To me, it doesn't really matter. I think DC would be pretty cool overall but, if you feel like you want to cred your work in a way, i'm totally fine with LM.

**Comment by legman** [comment]
Well thats the thing, its a collective effort. There will be some scripts written by other people - not just me.

**Comment by legman** [comment]
ok i've refactored everything i have made so far with DC!
